insert into chat."user"(login, password) values ('BlueberryBlast', '8r#hK7$5tL9z');
insert into chat."user"(login, password) values ('ElectricEagle', '3^G9@vKp#4s');
insert into chat."user"(login, password) values ('MysticMango', '6%t#7L@z2xK');
insert into chat."user"(login, password) values ('CosmicCactus', '1!sC9#kP8rJ3');
insert into chat."user"(login, password) values ('RainbowRider', '9@bX5#pL7rT2');
insert into chat."user"(login, password) values ('SilverSparrow', '4^wK9!tL7zR8');
insert into chat."user"(login, password) values ('OceanOtter', 'qwerty');
insert into chat."user"(login, password) values ('EmeraldElephant', 'qwertyuiop');
insert into chat."user"(login, password) values ('GoldenGazelle', 'asdfghjkl');
insert into chat."user"(login, password) values ('SapphireSeahorse', 'password');
insert into chat."user"(login, password) values ('RubyRabbit', '1234');
insert into chat."user"(login, password) values ('DiamondDolphin', '987654321');
insert into chat."user"(login, password) values ('CrimsonCrab', '8#sG2@kL4tR6');
insert into chat."user"(login, password) values ('LavenderLion', '9z$K8#pJ5rT2');
insert into chat."user"(login, password) values ('TurquoiseTurtle', '7!dF5#mN3tR9');
insert into chat."user"(login, password) values ('AmberAntelope', '6%tR8#pL7zK2');
insert into chat."user"(login, password) values ('JadeJaguar', '5^wT9!sM7xR8');
insert into chat."user"(login, password) values ('OnyxOwl', '4@bX6#nL8rS3');
insert into chat."user"(login, password) values ('TopazTiger', '3!sC8#kN7rJ4');
insert into chat."user"(login, password) values ('PearlPenguin', '2#dG7@lM5tR9');
insert into chat."user"(login, password) values ('TwentyFirst_User', '1$zK6#pJ4tT8');

insert into chat.chatroom(name, owner) values ('First_chatroom', 5);
insert into chat.chatroom(name, owner) values ('Second_chatroom', 4);
insert into chat.chatroom(name, owner) values ('Third_chatroom', 2);
insert into chat.chatroom(name, owner) values ('Fourth_chatroom', 3);
insert into chat.chatroom(name, owner) values ('Fifth_chatroom', 5);
insert into chat.chatroom(name, owner) values ('RainbowRoom', 3);
insert into chat.chatroom(name, owner) values ('SapphireSalon', 7);
insert into chat.chatroom(name, owner) values ('EmeraldEmporium', 12);
insert into chat.chatroom(name, owner) values ('TopazTavern', 9);
insert into chat.chatroom(name, owner) values ('AmberArcade', 1);
insert into chat.chatroom(name, owner) values ('JadeJoint', 18);
insert into chat.chatroom(name, owner) values ('OnyxOasis', 4);
insert into chat.chatroom(name, owner) values ('LavenderLounge', 15);
insert into chat.chatroom(name, owner) values ('TurquoiseTerrace', 21);
insert into chat.chatroom(name, owner) values ('PearlParlor', 6);

insert into chat.message(author, room, "Text")  values (1, 1, 'First_message');
insert into chat.message(author, room, "Text")  values (2, 3, 'Second_message');
insert into chat.message(author, room, "Text")  values (3, 3, 'Third_message');
insert into chat.message(author, room, "Text")  values (4, 4, 'Fourth_message');
insert into chat.message(author, room, "Text")  values (5, 2, 'Fifth_message');
insert into chat.message(author, room, "Text") values (5, 12, 'Hello, how are you?');
insert into chat.message(author, room, "Text") values (9, 3, 'What are you up to?');
insert into chat.message(author, room, "Text") values (1, 5, 'Nice to meet you!');
insert into chat.message(author, room, "Text") values (7, 9, 'How was your day?');
insert into chat.message(author, room, "Text") values (14, 2, 'What do you think about this?');
insert into chat.message(author, room, "Text") values (3, 11, 'I need some advice...');
insert into chat.message(author, room, "Text") values (11, 7, 'Have you heard about this?');
insert into chat.message(author, room, "Text") values (6, 4, 'Let me tell you a story...');
insert into chat.message(author, room, "Text") values (2, 10, 'I have a question...');
insert into chat.message(author, room, "Text") values (8, 1, 'This is so exciting!');
insert into chat.message(author, room, "Text") values (12, 6, 'I can''t believe it!');
insert into chat.message(author, room, "Text") values (15, 13, 'What''s your favorite color?');
insert into chat.message(author, room, "Text") values (4, 8, 'I''m feeling great today!');
insert into chat.message(author, room, "Text") values (10, 14, 'Let''s meet up sometime!');
insert into chat.message(author, room, "Text") values (13, 15, 'Do you like to travel?');
insert into chat.message(author, room, "Text") values (1, 6, 'I''m so tired...');
insert into chat.message(author, room, "Text") values (5, 8, 'What''s your favorite food?');
insert into chat.message(author, room, "Text") values (9, 2, 'I''m feeling a bit down...');
insert into chat.message(author, room, "Text") values (7, 11, 'I''m excited for the weekend!');
insert into chat.message(author, room, "Text") values (14, 4, 'Have you seen this movie?');
insert into chat.message(author, room, "Text") values (3, 13, 'I''m looking for a new hobby...');
insert into chat.message(author, room, "Text") values (11, 1, 'What''s your favorite book?');
insert into chat.message(author, room, "Text") values (6, 10, 'I''m feeling a bit lost...');
insert into chat.message(author, room, "Text") values (2, 7, 'I''m so excited for this!');
insert into chat.message(author, room, "Text") values (8, 3, 'What''s your favorite TV show?');
insert into chat.message(author, room, "Text") values (12, 12, 'I''m feeling a bit overwhelmed...');
insert into chat.message(author, room, "Text") values (15, 5, 'What''s your favorite hobby?');
insert into chat.message(author, room, "Text") values (4, 9, 'I''m feeling a bit anxious...');
insert into chat.message(author, room, "Text") values (10, 2, 'What''s your favorite movie?');
insert into chat.message(author, room, "Text") values (13, 14, 'I''m feeling a bit bored...');
insert into chat.message(author, room, "Text") values (1, 11, 'What''s your favorite music genre?');
insert into chat.message(author, room, "Text") values (20, 1, 'I''m feeling a bit stressed...');
insert into chat.message(author, room, "Text") values (9, 6, 'What''s your favorite animal?');
insert into chat.message(author, room, "Text") values (7, 12, 'I''m feeling a bit lonely...');
insert into chat.message(author, room, "Text") values (14, 3, 'What''s your favorite sport?');
insert into chat.message(author, room, "Text") values (19, 8, 'I''m feeling a bit happy...');
insert into chat.message(author, room, "Text") values (11, 15, 'What''s your favorite place to visit?');
insert into chat.message(author, room, "Text") values (6, 2, 'I''m feeling a bit tired...');
insert into chat.message(author, room, "Text") values (2, 13, 'What''s your favorite season?');
insert into chat.message(author, room, "Text") values (8, 7, 'I''m feeling a bit hungry...');
insert into chat.message(author, room, "Text") values (8, 7, 'Not i am.');